### ISSUE TITLE
Add support for webpack 5

### ISSUE THREAD

**Issue by niemyjski** [learningmachine/fw-loader#1]
Please Add support for webpack 5 :)

```
 Error: Can't find template for: ReadonlyField
    at _getTemplateFor (view-engine.js:172)
    at makeVueComponent (view-engine.js:182)
    at eval (fw.js:97)
    at Array.forEach (<anonymous>)
    at FrameworkConfig.registerComponents (fw.js:96)```

**Comment by derekpitt** [comment]
Sure man! I’m on vacation this week but I’ll take a look when I get back!

**Comment by raiseandfall** [comment]
Oh yeah that'd be nice

**Comment by niemyjski** [comment]
I was able to narrow it down this issue a little more. I'm not sure what's converting this to a module. I need to see what's setting this and converting it to a module. ![image](https://user-images.githubusercontent.com/1020579/122293031-3a2af780-cebc-11eb-9a85-672776e42e92.png)

**Comment by niemyjski** [comment]
@derekpitt did you have any chance to take a look at this?
